# -*- mode: ruby -*-
# vi: set ft=ruby :

require "yaml"

_config = YAML.load(File.open(File.join(File.dirname(__FILE__), "../../vagrantconfig.yaml"), File::RDONLY).read)

begin
    _config.merge!(YAML.load(File.open(File.join(File.dirname(__FILE__), "../../vagrantconfig_local.yaml"), File::RDONLY).read))
rescue Errno::ENOENT

end

CONF = _config

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.synced_folder "../../www", "/home/vagrant/www", :nfs => false, :owner => "vagrant"
  config.vm.synced_folder "../../puppet/files", "/etc/puppet/files", :nfs => false
  config.vm.network :private_network, ip: "192.168.33.10"
    config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.customize ["modifyvm", :id, "--name", "piwik-dev"]
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../../puppet"
    puppet.manifest_file  = "site.pp"
    puppet.module_path    = "../../puppet/modules"
    puppet.options = ['--verbose']
    puppet.facter = [
        ['db_username',  CONF['db_username']],
        ['db_password',  CONF['db_password']],
    ]
  end
end