# -*- mode: ruby -*-
# vi: set ft=ruby :

require "yaml"

_config = YAML.load(File.open(File.join(File.dirname(__FILE__), "../../vagrantconfig.yaml"), File::RDONLY).read)

begin
    _config.merge!(YAML.load(File.open(File.join(File.dirname(__FILE__), "../../vagrantconfig_local.yaml"), File::RDONLY).read))
rescue Errno::ENOENT

end

CONF = _config

Vagrant::Config.run do |config|
  config.vm.box     = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  
  config.vm.network :hostonly, "192.168.33.10"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../../puppet"
    puppet.manifest_file  = "site.pp"
    puppet.module_path    = "../../puppet/modules"
    puppet.facter = [
        ['db_username',  CONF['db_username']],
        ['db_password',  CONF['db_password']],
        ['repository',   CONF['repository']],
        ['svn_username', CONF['svn_password']],
        ['svn_password', CONF['svn_password']],
    ]

  end

end